%% train_cnn.m
% Train the twin (Siamese) CNN on natural-image near/far patch pairs, sampled
% fresh on the fly (never repeating). Test/validate on a balanced same/different
% texture-pair set combining several texture databases (cross-domain transfer),
% loaded from a .mat produced by general.texture_same_diff_patches_cnn.
% Run from the repo root with cnn/ on the MATLAB path (run setup first).

clearvars
clc

down_level = 1;     % resolution scale-down (1,2,4,8); MUST match the level used
                    % when generating the texture test pairs
gpu = gpuDevice([]);

%% Build the training data (natural-image near/far pairs, sampled on the fly)
% On-the-fly sampling (cnn_architecture_plan.md): build the pool of achromatic (A)
% source images once, then cut fresh, non-repeating patch pairs each iteration, so
% there is nothing to memorize. Settings mirror general.nat_near_far_patches_cnn.
imgdir = '../vislab-common/data/CPS natural images/'; % 16-bit linear source images
ppd = 60; pd = 4; w = 550;   % optics: pixels/deg, pupil diameter mm, wavelength nm
set_nums = [9 10 12];
n_imgs   = [104 90 197];
psz = 64;                    % patch size (matches the [64 64 1] network input)
same_max_dist = 1;           % max neighbor offset (in patches) for the near pair

% expensive one-time step: process every source image into its A channel
A_pool = general.load_nat_A_pool(imgdir,set_nums,n_imgs,ppd,pd,w,down_level);

% Split the IMAGE list (not pairs) into 90% train / 10% val, so validation patches
% come from images the network never trains on.
n_img = numel(A_pool);
perm = randperm(n_img);
nTrainImg = round(0.9 * n_img);
A_pool_train = A_pool(perm(1:nTrainImg));
A_pool_val   = A_pool(perm(nTrainImg+1:end));
% A_pool stays in CPU RAM; only the small per-batch arrays go to the GPU.

%% Load the texture test data (same/different pairs; Bayesian-mirrored ingestion)
% Generated by general.texture_same_diff_patches_cnn. Two test sets:
%   same,      diff       -- all databases combined (brodatz/fabric/mcgill/vistex/pertex,
%                            balanced), "different" pairs may cross databases
%   same_brod, diff_brod  -- Brodatz only
% label 1 = same texture, 0 = different.
if down_level>1
    bpfile = ['data/stimuli/textures/patch_pairs_dsmpl_' num2str(down_level) '.mat'];
else
    bpfile = 'data/stimuli/textures/patch_pairs.mat';
end
load(bpfile,'same','diff','same_brod','diff_brod');

%% Define Network Architecture
% shared subnetwork
layers = [
    imageInputLayer([64 64 1],Normalization=@(img) img/mean(img(:))) % 64x64
    convolution2dLayer(5,8,WeightsInitializer="narrow-normal",BiasInitializer="narrow-normal") % 60x60 x8
    reluLayer
    maxPooling2dLayer(2,Stride=2) % 30x30
    convolution2dLayer(5,16,WeightsInitializer="narrow-normal",BiasInitializer="narrow-normal") % 26x26 x16
    reluLayer
    maxPooling2dLayer(2,Stride=2) % 13x13
    convolution2dLayer(4,16,WeightsInitializer="narrow-normal",BiasInitializer="narrow-normal") % 10x10 x16
    reluLayer
    maxPooling2dLayer(2,Stride=2) % 5x5
    convolution2dLayer(2,32,WeightsInitializer="narrow-normal",BiasInitializer="narrow-normal") % 4x4 x32
    reluLayer]; % subnet outputs a 4x4x32 map; poolStats reduces it to a
                % 64-vector (32 channel means + 32 channel stds) per patch

net = dlnetwork(layers);

% merge with fully connected layer (architecture C: 64-d pooled embedding)
fcWeights = dlarray(0.01*single(randn(1,64))); % 64 = 32 channel means + 32 channel stds from poolStats
fcBias = dlarray(0.01*single(randn(1,1)));
fcParams = struct("FcWeights",fcWeights,"FcBias",fcBias);

%% train network
numIterations = 1.5e4;
miniBatchSize = 12288;
learningRate = 8e-4;
gradDecay = 0.9;
gradDecaySq = 0.99;
executionEnvironment = "auto";
trailingAvgSubnet = [];
trailingAvgSqSubnet = [];
trailingAvgParams = [];
trailingAvgSqParams = [];
% Create a standard figure with animated lines for precise color control
monitor_fig = figure('Name', 'Training Progress');
ax = axes(monitor_fig);
grid(ax, 'on');
xlabel(ax, 'Iteration');
ylabel(ax, 'Accuracy');
title(ax, 'Training and Validation Accuracy');

% Light blue, Mid blue, Orange, Green
lineTrain = animatedline(ax, 'DisplayName', 'training (nat)', 'Color', [0.3010 0.7450 0.9330], 'LineWidth', 1.5);
lineNatVal = animatedline(ax, 'DisplayName', 'test (nat)', 'Color', [0 0.4470 0.7410], 'LineWidth', 1.5);
lineTexVal = animatedline(ax, 'DisplayName', 'test (all textures)', 'Color', [1 0.6 0.6], 'LineWidth', 1.5);
lineBrodVal = animatedline(ax, 'DisplayName', 'test (Brodatz)', 'Color', [0.8 0.1 0.1], 'LineWidth', 1.5);
legend(ax, 'show', 'Location', 'southeast');

% OPTIMIZATION: Pre-load fixed texture validation batches to the GPU (all textures +
% Brodatz-only), each reused every check.
[XVal1,XVal2,valLabels] = getTwinBatchPairs(same,diff,miniBatchSize);
XVal1 = dlarray(single(gpuArray(XVal1)),"SSCB");
XVal2 = dlarray(single(gpuArray(XVal2)),"SSCB");
valLabels = gpuArray(valLabels);

[XValB1,XValB2,valLabelsB] = getTwinBatchPairs(same_brod,diff_brod,miniBatchSize);
XValB1 = dlarray(single(gpuArray(XValB1)),"SSCB");
XValB2 = dlarray(single(gpuArray(XValB2)),"SSCB");
valLabelsB = gpuArray(valLabelsB);

% The nat validation batch is drawn fresh from the held-out images at each check
% (inside the loop), not fixed here, so the NatVal curve is an average over many
% held-out pairs rather than one frozen sample.

start = tic;
iteration = 0;

% Loop over mini-batches.
while iteration < numIterations && isvalid(monitor_fig)
    iteration = iteration + 1;

    % Sample a fresh, never-repeating mini-batch of natural-image near/far pairs
    [X1,X2,pairLabels] = getTwinBatch_nat_live(A_pool_train,miniBatchSize,psz,same_max_dist);

    % Patches are cut on the CPU; move the finished batch to the GPU.
    X1 = dlarray(single(gpuArray(X1)),"SSCB");
    X2 = dlarray(single(gpuArray(X2)),"SSCB");
    pairLabels = gpuArray(pairLabels);

    % Evaluate the model loss on training images
    [training_loss,gradientsSubnet,gradientsParams] = dlfeval(@modelLoss,net,fcParams,X1,X2,pairLabels);

    % Measure training accuracy on THIS batch BEFORE the weight update. With the
    % on-the-fly sampler no pair ever repeats, so this batch is fresh data the
    % network has not trained on yet -- measuring it here is an honest held-out-style
    % number that lines up with the validation curves. (Measuring after the update,
    % as before, was optimistically biased because the step just moved the weights
    % toward these exact examples.)
    Y = predictTwin(net,fcParams,X1,X2);

    % OPTIMIZATION: compute accuracy on the GPU, only gather the final scalar
    Y = round(extractdata(Y));
    training_acc = gather(sum(Y == pairLabels)/miniBatchSize);

    % Update training line
    addpoints(lineTrain, iteration, training_acc);

    % Update the twin subnetwork parameters.
    [net,trailingAvgSubnet,trailingAvgSqSubnet] = adamupdate(net,gradientsSubnet, ...
        trailingAvgSubnet,trailingAvgSqSubnet,iteration,learningRate,gradDecay,gradDecaySq);

    % Update the fullyconnect parameters.
    [fcParams,trailingAvgParams,trailingAvgSqParams] = adamupdate(fcParams,gradientsParams, ...
        trailingAvgParams,trailingAvgSqParams,iteration,learningRate,gradDecay,gradDecaySq);

    if mod(iteration, 50) == 0 || iteration == 1
        % Evaluate predictions on the all-textures test set
        YVal = predictTwin(net,fcParams,XVal1,XVal2);
        YVal = round(extractdata(YVal));
        tex_val_acc = gather(sum(YVal == valLabels)/miniBatchSize);
        addpoints(lineTexVal, iteration, tex_val_acc);

        % Evaluate predictions on the Brodatz-only test set
        YValB = predictTwin(net,fcParams,XValB1,XValB2);
        YValB = round(extractdata(YValB));
        brod_val_acc = gather(sum(YValB == valLabelsB)/miniBatchSize);
        addpoints(lineBrodVal, iteration, brod_val_acc);

        % Draw a fresh nat validation batch from the held-out images each check, so
        % NatVal is a new random sample of held-out pairs every time rather than one
        % fixed batch. Kept on held-out images (not the training images) so it still
        % measures generalization to unseen scenes.
        [XValNat1,XValNat2,valLabelsNat] = getTwinBatch_nat_live(A_pool_val,miniBatchSize,psz,same_max_dist);
        XValNat1 = dlarray(single(gpuArray(XValNat1)),"SSCB");
        XValNat2 = dlarray(single(gpuArray(XValNat2)),"SSCB");
        valLabelsNat = gpuArray(valLabelsNat);

        % Evaluate natural image validation accuracy
        YValNat = predictTwin(net,fcParams,XValNat1,XValNat2);
        YValNat = round(extractdata(YValNat));
        nat_val_acc = gather(sum(YValNat == valLabelsNat)/miniBatchSize);
        addpoints(lineNatVal, iteration, nat_val_acc);
        drawnow;
    else
        drawnow limitrate;
    end
end

%% save the trained network
if down_level>1
    netfile = ['net_on_nat_dsmpl_' num2str(down_level) '.mat'];
else
    netfile = 'net_on_nat.mat';
end
save(netfile,'net','fcParams')

% Save the training monitor plot to the script's folder
if isvalid(monitor_fig)
    timestamp = char(datetime('now', 'Format', 'yyyy-MM-dd_HH-mm-ss'));
    script_dir = fileparts(mfilename('fullpath'));
    if isempty(script_dir)
        % Fallback if running code interactively (e.g. evaluating selection)
        if exist('cnn', 'dir')
            script_dir = 'cnn';
        else
            script_dir = '.';
        end
    end
    savePath = fullfile(script_dir, ['training_monitor_' timestamp '.png']);
    
    % Since it's a standard figure now, exportgraphics works perfectly
    exportgraphics(monitor_fig, savePath, 'Resolution', 300);
end

%% Test accuracy over five random mini-batches of texture test pairs
accuracy = zeros(1,5);
accuracyBatchSize = 512;

for i = 1:5
    [X1,X2,pairLabelsAcc] = getTwinBatchPairs(same,diff,accuracyBatchSize);
    X1 = dlarray(single(gpuArray(X1)),"SSCB");
    X2 = dlarray(single(gpuArray(X2)),"SSCB");
    Y = predictTwin(net,fcParams,X1,X2);
    Y = gather(extractdata(Y));
    Y = round(Y);
    accuracy(i) = sum(Y == pairLabelsAcc)/accuracyBatchSize;
end

averageAccuracy = mean(accuracy)*100

%% Display test pairs with predictions
testBatchSize = 20;

[XTest1,XTest2,pairLabelsTest] = getTwinBatchPairs(same,diff,testBatchSize);

XTest1 = dlarray(single(gpuArray(XTest1)),"SSCB");
XTest2 = dlarray(single(gpuArray(XTest2)),"SSCB");

% calculate predicted probability
YScore = predictTwin(net,fcParams,XTest1,XTest2);
YScore = gather(extractdata(YScore));

% Convert the predictions to binary 0 or 1.
YPred = round(YScore);
XTest1 = extractdata(XTest1);
XTest2 = extractdata(XTest2);

% Plot images with predicted label and predicted score.
f = figure;
tiledlayout(4,5);

predLabels = categorical(YPred,[0 1],["diff" "same"]);
targetLabels = categorical(pairLabelsTest,[0 1],["diff","same"]);

for i = 1:numel(pairLabelsTest)
    nexttile
    imshow([XTest1(:,:,:,i) XTest2(:,:,:,i)],[]);
    title(string(targetLabels(i)) + " / " + ...
        string(predLabels(i)) + newline + YScore(i))
end
